### ISSUE TITLE
a word about portacle !

### ISSUE THREAD

**Issue by vindarel** [rmhsilva/lispmethods#1]
Hi !
it can be really worth saying a word about [Portacle](https://shinmera.github.io/portacle/) IMO, the multiplatform and portable lisp environment ! (Emacs, SBCL, Quicklisp, Git, no installation needed).

cheers !

**Comment by rmhsilva** [comment]
Yep absolutely! The info on lispmethods is still very much "in development", I'm writing as fast as I can ;).

I intend to mention https://shinmera.github.io/portacle/ and https://github.com/roswell/roswell in the getting started guide.

Thanks for the suggestion!
