### ISSUE TITLE
Thanks for this awesome work.

### ISSUE THREAD

**Issue by azzamsa** [rmhsilva/lispmethods#3]
Happy Hacking.!

**Comment by imnisen** [comment]
Also appreciated to let me figure out what "symbol" is

**Comment by rmhsilva** [comment]
@azzamsa, @imnisen I'm glad it has been useful to you! Thanks for the feedback :). 

I haven't abandoned this, just haven't figured out what to write about next.

**Comment by azzamsa** [comment]
Keep flying :)
