### ISSUE TITLE
go on with lispmethods!

### ISSUE THREAD

**Issue by gwangjinkim** [rmhsilva/lispmethods#5]
As an encouragement to you, Ric,
please go on with lispmethods!

By the way, do you know: https://leanpub.com/lovinglisp/read ?

I just recently stumbled on it. It might give you some inspiration. Because modern stuff is covered there.

There are too few - compared to the other languages - introductory stuff there.

Recently I stumbled on an I/O problem: common lisp cannot read-in xlsx files directly or write to it. There is no simple solution for that.
The packages :xlsx and :lisp-xl couldn't read my libreoffice-generated .xlsx files properly, although they were very basic ...
There are solutions with ABCL using Java stuff ...

I am trying to get into and understand :xlsx first ... (but I am very new to this stuff ... it takes me ages to write some code using cl ...)
maybe will try an own small package to address this issue ...

Just wanted to tell the overall idea to collect information and provide solutions for up-to-date and everyday problems with common lisp is really good and to be supported! :)

We have to spread lisp - the best and most underestimated computer language in the world. :)

**Comment by gwangjinkim** [comment]
And wherever I can help you - just tell me!

**Comment by lisp-is-the-future** [comment]
Ah and by the way, this repo I created to collect all the lisp stuff (I am gwangjinkim). But it is still empty. To be changed ... :)
