### ISSUE TITLE
Is this site active?

### ISSUE THREAD

**Issue by goranmoomin** [rmhsilva/lispmethods#6]
I really believe it is... I really love this site :-)

**Comment by rmhsilva** [comment]
There are plans to publish more content, but that may not happen in the very near future! However the site won't go away any time soon.

**Comment by goranmoomin** [comment]
I hope to see some more content, @rmhsilva! I truly love this blog :-)

**Comment by rmhsilva** [comment]
Alright @pcr910303, I'll try!
